# Generated by Django 2.2.2 on 2019-09-13 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('vendorcode', models.CharField(max_length=100, unique=True)),
                ('price', models.IntegerField(default=0)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='paperdetail', serialize=False, to='products.Product')),
                ('format', models.CharField(max_length=50)),
                ('sheets', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Pen',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pendetail', serialize=False, to='products.Product')),
                ('color', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('feather', 'перьевая'), ('ball', 'шариковая')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pencil',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pencildetail', serialize=False, to='products.Product')),
                ('color', models.CharField(max_length=50)),
                ('hardness', models.CharField(max_length=50)),
            ],
        ),
    ]
